FROM maven:3-openjdk-18 AS builder

WORKDIR /app

COPY ./mvnw .
COPY ./mvnw.cmd .
COPY ./pom.xml .
COPY ./src src

# build
RUN mvn package

FROM openjdk:18-oracle

WORKDIR /app

COPY --from=builder /app/target/question2-0.0.1.jar question2.jar

EXPOSE 8080

ENTRYPOINT [ "java", "-jar", "question2.jar" ]
